### ISSUE TITLE
Extract Pipeline class

### ISSUE THREAD

**Issue by janwalther** [dantleech/p-meter#2]
I really like the implementation of the Pipeline class as it supports generators. Would you mind extracting it to a separate repository?

**Comment by dantleech** [comment]
I'd rather not, as this is just an experimental project - but maybe worth investigating if you can make generator processor implementation for https://github.com/thephpleague/pipeline ?

But in any-case feel free to extract the relevant classes to a new repository of your own (creditation appreciated). :)

**Comment by janwalther** [comment]
Hehe, understood. Already opened an [issue at theleague/pipeline](https://github.com/thephpleague/pipeline/issues/44). Hopefully I will find some time to implement it soon. 
Nevertheless, thanks for your presentation at IPC!
